### ISSUE TITLE
Incomplete instructions for jspm-git use

### ISSUE THREAD

**Issue by adriatic** [JeroenVinke/aurelia-kendoui-jspm-git#1]
The [lines](https://github.com/JeroenVinke/aurelia-kendoui-jspm-git/edit/master/README.md#L5-6) are necessary but **not sufficient** to create the proper data in the `config` file. In addition you need to run `jspm registry config jspm-git` and when prompted, enter your Telerik credentials (as you know, jspm-git endpoint is previously instructed to access `https://bower.telerik.com`)

Once this information is in the `...\AppData\Local\.jspm\config` file (remember my `auth=0` entry) the step `jspm install` **should not need to ask you for credentials**.

I left all this to do yourself - and once you update the [repo](aurelia-kendoui-jspm-git) I will test it again on my machine

I bet that this removes the need for "consultation with Charles" :-)

**Comment by adriatic** [comment]
**Note** my above conclusion draws from https://github.com/jspm/jspm-cli/issues/1300

**Comment by JeroenVinke** [comment]
This is awesome. I will edit the readme.

**Comment by JeroenVinke** [comment]
@adriatic I have updated the first part of the readme: https://github.com/JeroenVinke/aurelia-kendoui-jspm-git/blob/master/README.md#steps-to-run-this-app.

If you can confirm this is working for you, i'll update the second part of the readme

**Comment by JeroenVinke** [comment]
BTW, this would mean we wouldn't have to make changes to jspm-git :)
